
require 'sinatra'

set :port, 9000

def hello
    def hello2
        return " : nested function"
    end
    def hello3
        return ": __from hello3 function__"
    end
    def add(num1, num2)
        # string template
        return "__string generated by add function __ #{num1 + num2} "
    end
    print add 22,33
    puts "background output ... "
    # must use parenthesis
    return "==__==" + hello2 + hello3() + add(11,22)
end

get '/' do
    "Hello, World!" + "<br>" + hello
end