# frozen_string_literal: true

#source "https://rubygems.org"
source "https://gems.ruby-china.com/"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# gem 'rails', '5.2.0'
gem 'rails', '4.2.10'
